<a href="https://colab.research.google.com/github/Mafred02/Programacion/blob/main/Semana9(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Manejo de módulos integrados

Pandas (Datos como Excel[base de datos]), Numpy (Datos numericos[matrices])

In [2]:
import numpy as np

.array (arreglo) enfocado para calculos

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]

In [47]:
lista = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lista*2)
print(arr*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]

In [29]:
b.shape

(2, 2)

shape (dimension)

In [13]:
print(arr.ndim)
print(b.ndim)

1
2

.ndim (cuenta filas)

In [17]:
print(b.dtype, arr.dtype)

int64 int64

In [18]:
b.size

4

.size (cuenta columnas)

In [23]:
print(np.zeros((2,3)))
print(np.ones((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]

.zeros rellena de 0 la matriz de 2 elementos con 3 componentes (elemento = fila, componente = columna)
.ones (unos)

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

.eye (matriz identidad)

In [27]:
np.arange(0, 10, 4)

array([0, 4, 8])

.arange va desde 0 hasta 10 de a 4

In [33]:
np.linspace(0, 3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

.linspace (va de 0 a 3, partiendo en 5 puntos de igual distancia al otro)

In [36]:
arry = np.array([10, 20, 30, 40])
arry[0]

np.int64(10)

In [37]:
arry[-1]

np.int64(40)

In [38]:
arry[0:2]

array([10, 20])

In [41]:
matri = np.array([[1,2,3],[4,5,6]])
matri[0,1]

np.int64(2)

elemento (0,1) es decir el 2

In [49]:
matri[:,0]

array([1, 4])

(:,0) primera columna, matri(1,:) segunda fila

In [50]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [51]:
a * b #producto de Hadamard entre dos arreglos

array([ 4, 10, 18])

In [52]:
matri1 = np.array([[2,3,3],[4,5,6]])
matri1*matri

array([[ 2,  6,  9],
       [16, 25, 36]])

In [55]:
c = np.array([1.65, 1.58, 1.82, 1.70, 1.50, 1.82, 1.74])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))

1.6871428571428573 1.7 0.11093296376181246 11.81 1.5 1.82

.mean() (**promedio**)

.median() (**mediana**)

.std() (**desviacion estandar**)

.sum() (**sumatoria**)

.min() (**minimo**)

.max() (**maximo**)

In [58]:
d = np.array([1,2,3,4,5,6])
d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

.reshape() redimensiona

In [65]:
np.concatenate((d.reshape(2,3), matri))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
np.concatenate((d.reshape(2,3)))

array([1, 2, 3, 4, 5, 6])

concatena dos arreglos( deben tener misma dimension)

In [67]:
d.reshape(2,3).flatten()

array([1, 2, 3, 4, 5, 6])

.flatten() vectoriza

In [69]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

Producto de matrices

In [70]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Inversa de una matriz

In [72]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

determinante

In [73]:
np.linalg.matrix_transpose(a)

array([[1, 3],
       [2, 4]])

la transpuesta

In [74]:
np.random.rand(10)

array([0.12422178, 0.50637075, 0.7766031 , 0.44824111, 0.63630083,
       0.35741701, 0.56846393, 0.69978849, 0.51031783, 0.34210943])

10 valores aleatorios de una distribucion uniforme en el intervalo (0,1)

In [126]:
np.random.randint(0,10)

0

valor entero entre 0 y 10(excepto este ultimo)

In [127]:
np.random.randn(8)

array([-0.97244282,  0.04973317, -1.80195132,  0.96058861,  0.13138733,
       -0.2336583 ,  0.56960509, -0.93214619])

Genera 8 valores aleatorios de una distribucion normal con media 0 y desviacion estandar 1

In [132]:
e = np.array([1,2,3,4,5])
e[e > 3]

array([4, 5])

In [134]:
e[(e > 2) & (e < 5)] #note que & es y y o es |

array([3, 4])

filtra

In [139]:
np.where(e > 3, 1, 0)

array([0, 0, 0, 1, 1])

In [137]:
np.where(e > 3, 1, e)

array([1, 2, 3, 1, 1])

reemplaza por 1 a los valores mayores a 3

In [167]:
x = np.arange(1,11)
print(x)
print(x*5)
print(x[x > 5])
print(np.arange(9).reshape(3,3))
print(np.mean(x))
print(np.std(x))

[ 1  2  3  4  5  6  7  8  9 10]
[ 5 10 15 20 25 30 35 40 45 50]
[ 6  7  8  9 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
5.5
2.8722813232690143

Pandas

In [170]:
import pandas as pd

In [175]:
s = pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [176]:
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1500, 2000, 3000, 2500]
}) # creando data.frames
df

   nombre    ciudad  edad  salario
0     Ana    Bogotá    23     1500
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

tabla

In [177]:
df.head(2)

  nombre    ciudad  edad  salario
0    Ana    Bogotá    23     1500
1   Luis  Medellín    30     2000

los primeros dos de la cabeza

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64
 3   salario  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

informacion

In [179]:
df.describe()

            edad      salario
count   4.000000     4.000000
mean   29.000000  2250.000000
std     4.966555   645.497224
min    23.000000  1500.000000
25%    26.750000  1875.000000
50%    29.000000  2250.000000
75%    31.250000  2625.000000
max    35.000000  3000.000000

estadisticas descriptivas para variables cuantitativas

In [180]:
df.shape

(4, 4)

In [181]:
df['edad']

0    23
1    30
2    35
3    28
Name: edad, dtype: int64

In [184]:
df[['nombre', 'edad']]

   nombre  edad
0     Ana    23
1    Luis    30
2  Carlos    35
3   Marta    28

Note que es una lista para poner dos

In [185]:
df[df['edad'] > 25]

   nombre    ciudad  edad  salario
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [186]:
df[(df['edad'] > 20) & (df['edad'] < 40)]

   nombre    ciudad  edad  salario
0     Ana    Bogotá    23     1500
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [222]:
data = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
    'edad': [23, np.nan, 35, 23, 40],
    'salario': [1000, 2000, None, 1000, 5000],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']
})
data

   nombre  edad  salario    ciudad
0     Ana  23.0   1000.0    Bogotá
1    Luis   NaN   2000.0  Medellín
2  Carlos  35.0      NaN      Cali
3     Ana  23.0   1000.0    Bogotá
4    None  40.0   5000.0      Cali

In [223]:
data.isnull()

   nombre   edad  salario  ciudad
0   False  False    False   False
1   False   True    False   False
2   False  False     True   False
3   False  False    False   False
4    True  False    False   False

True = Hay dato, False = No hay dato

In [224]:
data.isnull().sum()

nombre     1
edad       1
salario    1
ciudad     0
dtype: int64

si es true = 1, si es false = 0, entonces suma todas y muestra en donde hay valores nulos

In [225]:
data1 = data.dropna()
data1

  nombre  edad  salario  ciudad
0    Ana  23.0   1000.0  Bogotá
3    Ana  23.0   1000.0  Bogotá

elimina las filas con valores faltantes

In [226]:
data.dropna(subset=['salario'])

  nombre  edad  salario    ciudad
0    Ana  23.0   1000.0    Bogotá
1   Luis   NaN   2000.0  Medellín
3    Ana  23.0   1000.0    Bogotá
4   None  40.0   5000.0      Cali

Se eliminan las filas con valores faltantes, unicamente en la columna "salario"

In [227]:
data['edad'] = data['edad'].fillna(data['edad'].mean()) #reemplaze en la columna edad de mi base de datos con: La columna cuyos valores faltantes se llena con la mediana de dicha columna
data['nombre'] = data['nombre'].fillna("Desconocido")
data

        nombre   edad  salario    ciudad
0          Ana  23.00   1000.0    Bogotá
1         Luis  30.25   2000.0  Medellín
2       Carlos  35.00      NaN      Cali
3          Ana  23.00   1000.0    Bogotá
4  Desconocido  40.00   5000.0      Cali

In [228]:
data['ciudad'] = data['ciudad'].replace('Bogotá', 'BOGOTA')
data

        nombre   edad  salario    ciudad
0          Ana  23.00   1000.0    BOGOTA
1         Luis  30.25   2000.0  Medellín
2       Carlos  35.00      NaN      Cali
3          Ana  23.00   1000.0    BOGOTA
4  Desconocido  40.00   5000.0      Cali

In [232]:
data2 = data["ciudad"].drop_duplicates()
data2

0      BOGOTA
1    Medellín
2        Cali
Name: ciudad, dtype: object

In [234]:
dfn = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nombre': [' Ana', 'LUIS ', 'Carlos', 'ana'],
    'edad': [23, 30, 35, 28],
    'salario': [1000, 2000, 3000, 1500],
    'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín']
})
dfn

   id  nombre  edad  salario    ciudad
0   1     Ana    23     1000    Bogotá
1   2   LUIS     30     2000      Cali
2   3  Carlos    35     3000    Bogotá
3   4     ana    28     1500  Medellín

In [240]:
dfn['salario_anual'] = dfn['salario'] * 12
dfn['edad_doble'] = dfn['edad'].apply(lambda x:x * 2)
dfn

   id  nombre  edad  salario    ciudad  salario_anual  edad_doble
0   1     Ana    23     1000    Bogotá          12000          46
1   2   LUIS     30     2000      Cali          24000          60
2   3  Carlos    35     3000    Bogotá          36000          70
3   4     ana    28     1500  Medellín          18000          56

In [243]:
dfn = dfn.rename(columns = {'edad' : 'age'})
dfn

   id  nombre  age  salario    ciudad  salario_anual  edad_doble
0   1     Ana   23     1000    Bogotá          12000          46
1   2   LUIS    30     2000      Cali          24000          60
2   3  Carlos   35     3000    Bogotá          36000          70
3   4     ana   28     1500  Medellín          18000          56

In [251]:
dfn['nombre'] = dfn['nombre'].str.lower()
dfn['nombre'] = dfn['nombre'].str.strip()
dfn['nombre'] = dfn['nombre'].str.replace("ana", "JANA")
dfn

   id  nombre  age  salario    ciudad  salario_anual  edad_doble
0   1    JANA   23     1000    Bogotá          12000          46
1   2    luis   30     2000      Cali          24000          60
2   3  carlos   35     3000    Bogotá          36000          70
3   4    JANA   28     1500  Medellín          18000          56

In [252]:
grupo = dfn.groupby('ciudad')['salario'].mean()
grupo

ciudad
Bogotá      2000.0
Cali        2000.0
Medellín    1500.0
Name: salario, dtype: float64

In [253]:
ordenado = dfn.sort_values(by='age')
ordenado

   id  nombre  age  salario    ciudad  salario_anual  edad_doble
0   1    JANA   23     1000    Bogotá          12000          46
3   4    JANA   28     1500  Medellín          18000          56
1   2    luis   30     2000      Cali          24000          60
2   3  carlos   35     3000    Bogotá          36000          70

In [259]:
dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'departamento': ['Ventas', 'IT', 'RRHH', 'Marketing']
})

merge = pd.merge(dfn, dfn1, on="id")
merge

   id  nombre  age  salario    ciudad  salario_anual  edad_doble departamento
0   1    JANA   23     1000    Bogotá          12000          46       Ventas
1   2    luis   30     2000      Cali          24000          60           IT
2   3  carlos   35     3000    Bogotá          36000          70         RRHH
3   4    JANA   28     1500  Medellín          18000          56    Marketing

In [257]:
valores = dfn.values
valores

array([[1, 'JANA', 23, 1000, 'Bogotá', 12000, 46],
       [2, 'luis', 30, 2000, 'Cali', 24000, 60],
       [3, 'carlos', 35, 3000, 'Bogotá', 36000, 70],
       [4, 'JANA', 28, 1500, 'Medellín', 18000, 56]], dtype=object)

In [258]:
arr = np.array([10, 20, 30])
df = pd.DataFrame(arr)
df

    0
0  10
1  20
2  30